### ISSUE TITLE
Q: Consul leadership not working?

### ISSUE THREAD

**Issue by jvrplmlmn** [seatgeek/nomad-firehose#10]
I'm running multiple instances of `nomad-firehose` (each instance on a different box) and I've noticed that all of them produce the same output, it seems like the leadership mechanism is not working:

```
$ consul --version
Consul v0.9.3
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```

```
$ nomad --version
Nomad v0.6.0
```

```
$ SINK_TYPE=stdout ./nomad-firehose-linux-amd64 evaluations
INFO[0000] Trying to acquire leader lock
INFO[0000] Lock acquired
INFO[0000] No Last Change Time restore point, starting from scratch
{"ID":"687332a6-679f-e913-1b9c-a91528a9eba8","Priority":50,"Type":"service","TriggeredBy":"deployment-watcher","JobID":"XXX","JobModifyIndex":0,"NodeID":"","NodeModifyIndex":0,"DeploymentID":"3c22e031-cb8a-f8e2-9923-4e715e78c57c","Status":"complete","StatusDescription":"","Wait":0,"NextEval":"","PreviousEval":"","BlockedEval":"","FailedTGAllocs":null,"ClassEligibility":null,"EscapedComputedClass":false,"AnnotatePlan":false,"QueuedAllocations":{"XXX":0},"SnapshotIndex":1573880,"CreateIndex":1573880,"ModifyIndex":1573883}
{"ID":"24fe786e-8f94-3558-62e7-0c11bfea960d","Priority":50,"Type":"service","TriggeredBy":"deployment-watcher","JobID":"XXX","JobModifyIndex":0,"NodeID":"","NodeModifyIndex":0,"DeploymentID":"3c22e031-cb8a-f8e2-9923-4e715e78c57c","Status":"complete","StatusDescription":"","Wait":0,"NextEval":"","PreviousEval":"","BlockedEval":"","FailedTGAllocs":null,"ClassEligibility":null,"EscapedComputedClass":false,"AnnotatePlan":false,"QueuedAllocations":{"XXX":0},"SnapshotIndex":1573868,"CreateIndex":1573868,"ModifyIndex":1573870}
(...)
INFO[0010] Writing lastChangedTime to KV: 1573883
INFO[0020] Writing lastChangedTime to KV: 1573883
INFO[0030] Writing lastChangedTime to KV: 1573883
INFO[0040] Writing lastChangedTime to KV: 1573883
INFO[0050] Writing lastChangedTime to KV: 1573883
INFO[0060] Writing lastChangedTime to KV: 1573883
INFO[0070] Writing lastChangedTime to KV: 1573883
INFO[0080] Writing lastChangedTime to KV: 1573883
INFO[0090] Writing lastChangedTime to KV: 1573883
INFO[0100] Writing lastChangedTime to KV: 1573883
INFO[0110] Writing lastChangedTime to KV: 1573883
INFO[0120] Writing lastChangedTime to KV: 1573883
INFO[0130] Writing lastChangedTime to KV: 1573883
INFO[0140] Writing lastChangedTime to KV: 1573883
INFO[0150] Writing lastChangedTime to KV: 1573883
INFO[0160] Writing lastChangedTime to KV: 1573883
INFO[0170] Writing lastChangedTime to KV: 1573883
INFO[0180] Writing lastChangedTime to KV: 1573883
INFO[0190] Writing lastChangedTime to KV: 1573883
INFO[0200] Writing lastChangedTime to KV: 1573883
INFO[0210] Writing lastChangedTime to KV: 1573883
INFO[0220] Writing lastChangedTime to KV: 1573883
INFO[0230] Writing lastChangedTime to KV: 1573883
INFO[0240] Writing lastChangedTime to KV: 1573883
INFO[0250] Writing lastChangedTime to KV: 1573883
INFO[0260] Writing lastChangedTime to KV: 1573883
INFO[0270] Writing lastChangedTime to KV: 1573883
INFO[0280] Writing lastChangedTime to KV: 1573883
INFO[0290] Writing lastChangedTime to KV: 1573883
INFO[0300] Writing lastChangedTime to KV: 1573883
INFO[0310] Writing lastChangedTime to KV: 1573883
^CINFO[0316] Caught signal, releasing lock and stopping...
INFO[0316] [sink/stdout] ensure writer queue is empty (0 messages left)
INFO[0316] Writing lastChangedTime to KV: 1573883
```

Am I doing something wrong? 🤔

**Comment by jvrplmlmn** [comment]
@jippi any chance that you could take a look at this issue?

**Comment by margueritepd** [comment]
@jvrplmlmn Looks like acquiring and releasing the lock happens in the [`NewFirehose`](https://github.com/seatgeek/nomad-firehose/blob/master/command/deployments/app.go#L39) function.
Maybe it should be happening in [`Start`](https://github.com/seatgeek/nomad-firehose/blob/master/command/deployments/app.go#L67)

**Comment by wyattanderson** [comment]
Can confirm that this is the case; I noticed this when testing #19. It appears the `New*` functions immediately release the lock after acquisition.

**Comment by scalp42** [comment]
@jippi any chance you can take a look?

**Comment by jippi** [comment]
ah, i think i've found the bug - kinda silly issue, let me try and come up with a patch for it

**Comment by jippi** [comment]
Fixed https://github.com/seatgeek/nomad-firehose/releases/tag/v1.0.0

the code was totally broken :p

**Comment by wyattanderson** [comment]
I think this is still broken. With this `docker-compose.yml` with self-contained Consul, Zookeeper, Kafka, and one instance of `nomad-firehose`, I'm still able to run two producer instances of `nomad-firehose` at the same time:

```
version: '3.5'

services:
  consul:
    image: consul
    environment:
      CONSUL_BIND_INTERFACE: eth0
  nomad-firehose:
    image: seatgeek/nomad-firehose:v1.0.0
    depends_on:
      - consul
    # change jobs to allocations or nodes or whatever
    command: nomad-firehose jobs
    environment:
      NOMAD_ADDR: YOUR_NOMAD_CLUSTER_HERE
      NOMAD_REGION: ...
      NOMAD_CACERT: ...
      SINK_TYPE: kafka
      SINK_KAFKA_BROKERS: kafka:29092
      SINK_KAFKA_TOPIC: foo
      CONSUL_HTTP_ADDR: http://consul:8500
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "moby:127.0.0.1"
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092:9092
    extra_hosts:
      - "moby:127.0.0.1"
```

This alone works great, I can follow along the Kafka topic, but when I try to start another `nomad-firehose` instance, it sits and waits 15 seconds for the lock, but then gives up and starts writing anyway:

```
$ docker-compose run --rm --no-deps nomad-firehose
INFO[0000] Trying to acquire leader lock (nomad-firehose/jobs.lock)
INFO[0015] Lock acquired
INFO[0015] Restoring Last Change Time to 62731127
INFO[0015] [sink/kafka] Starting writer
```

The other producer continues writing and doesn't try to reacquire the lock. At this point, we start seeing duplicate events on the Kafka topic.

Is this expected behavior?

**Comment by jippi** [comment]
@wyattanderson after 3h of weekend coding, i ended up refactoring everything - it should be `latest` and [1.1.0](https://github.com/seatgeek/nomad-firehose/releases/tag/1.1.0) tag 

I did some basic testing, and it seem to be working as expected. Let me know what you experience

**Comment by wyattanderson** [comment]
Excellent. Looks like it works now. Thanks so much!
